[[main]]
  name = "Aktivitetskalender"
  url = "/aktivitetskalender/"
  weight = 20

[[main]]
  name = "Vores klub"
  url = "/om-os/"
  weight = 30

[[main]]
  name = "Kontakt"
  url = "/kontakt"
  weight = 40
