[[main]]
  name = "Forside"
  url = "/index"
  weight = 10

[[main]]
  name = "Aktivitetskalender"
  url = "/aktivitetskalender/"
  weight = 20

[[main]]
  name = "Vores klub"
  url = "/om-os/"
  weight = 30

[[main]]
  name = "Kontakt"
  url = "/kontakt/"
  weight = 40

# [[main]]
  name = "AICurious"
  url = "https://aicurious.io/"
  parent = "Links"
  weight = 10

# [[main]]
  name = "HUGO Framework"
  url = "https://gohugo.io/"
  parent = "Links"
  weight = 20

# [[main]]
  name = "<img src=\"/icons/mail.svg\" style=\"height:1.2rem; display: inline; margin: 0;\">"
  url = "/contact/"
  weight = 50

# [[main]]
  name = "<img src=\"/icons/search.svg\" style=\"height:1.2rem; display: inline; margin: 0;\">"
  url = "/search/"
  weight = 60